/*
 * COPYRIGHT(C) 2011 FUJITSU LIMITED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
#ifndef _FJ_TOUCH_CONFIG_H_
#define _FJ_TOUCH_CONFIG_H_

#define MXT_CONFIG_CRC                    0xBB5456

/* GEN_COMMANDCONFIG_T6 */
#define MXT_CONFIG_T06_RESET              0
#define MXT_CONFIG_T06_BACKUPNV           0
#define MXT_CONFIG_T06_CALIBRAT           0
#define MXT_CONFIG_T06_REPORTALL          0
#define MXT_CONFIG_T06_DIAGNOSTIC         0

/* SPT_USERDATA_T38 */
#define MXT_CONFIG_T38_DATA_0             0
#define MXT_CONFIG_T38_DATA_1             0
#define MXT_CONFIG_T38_DATA_2             0
#define MXT_CONFIG_T38_DATA_3             0
#define MXT_CONFIG_T38_DATA_4             0
#define MXT_CONFIG_T38_DATA_5             0
#define MXT_CONFIG_T38_DATA_6             0
#define MXT_CONFIG_T38_DATA_7             0

/* GEN_POWERCONFIG_T7 */
#define MXT_CONFIG_T07_IDLEACQINT         16
#define MXT_CONFIG_T07_ACTVACQINT         17
#define MXT_CONFIG_T07_ACTV2IDLETO        50

/* GEN_ACQUISITIONCONFIG_T8 */
#define MXT_CONFIG_T08_CHRGTIME           20
#define MXT_CONFIG_T08_ATCHDRIFT          0
#define MXT_CONFIG_T08_TCHDRIFT           5
#define MXT_CONFIG_T08_DRIFTST            0
#define MXT_CONFIG_T08_TCHAUTOCAL         0
#define MXT_CONFIG_T08_SYNC               0
#define MXT_CONFIG_T08_ATCHCALST          4
#define MXT_CONFIG_T08_ATCHCALSTHR        35
#define MXT_CONFIG_T08_ATCHFRCCALTHR      3
#define MXT_CONFIG_T08_ATCHFRCCALRATIO    25

/* TOUCH_MULTITOUCHSCREEN_T9 */
#define MXT_CONFIG_T09_CTRL               139
#define MXT_CONFIG_T09_XORIGIN            0
#define MXT_CONFIG_T09_YORIGIN            0
#define MXT_CONFIG_T09_XSIZE              19
#define MXT_CONFIG_T09_YSIZE              11
#define MXT_CONFIG_T09_AKSCFG             0
#define MXT_CONFIG_T09_BLEN               32
#define MXT_CONFIG_T09_TCHTHR             71
#define MXT_CONFIG_T09_TCHDI              1
#define MXT_CONFIG_T09_ORIENT             1
#define MXT_CONFIG_T09_MRGTIMEOUT         10
#define MXT_CONFIG_T09_MOVHYSTI           3
#define MXT_CONFIG_T09_MOVHYSTN           1
#define MXT_CONFIG_T09_MOVFILTER          46
#define MXT_CONFIG_T09_NUMTOUCH           5
#define MXT_CONFIG_T09_MRGHYST            20
#define MXT_CONFIG_T09_MRGTHR             50
#define MXT_CONFIG_T09_AMPHYST            5
#define MXT_CONFIG_T09_XRANGE_LO          31
#define MXT_CONFIG_T09_XRANGE_HI          3
#define MXT_CONFIG_T09_YRANGE_LO          223
#define MXT_CONFIG_T09_YRANGE_HI          1
#define MXT_CONFIG_T09_XLOCLIP            1
#define MXT_CONFIG_T09_XHICLIP            1
#define MXT_CONFIG_T09_YLOCLIP            3
#define MXT_CONFIG_T09_YHICLIP            3
#define MXT_CONFIG_T09_XEDGECTRL          226
#define MXT_CONFIG_T09_XEDGEDIST          45
#define MXT_CONFIG_T09_YEDGECTRL          223
#define MXT_CONFIG_T09_YEDGEDIST          80
#define MXT_CONFIG_T09_JUMPLIMIT          32
#define MXT_CONFIG_T09_TCHHYST            15
#define MXT_CONFIG_T09_XPITCH             0
#define MXT_CONFIG_T09_YPITCH             0
#define MXT_CONFIG_T09_NEXTTCHDI          0

/* TOUCH_KEYARRAY_T15 */
#define MXT_CONFIG_T15_CTRL               0
#define MXT_CONFIG_T15_XORIGIN            0
#define MXT_CONFIG_T15_YORIGIN            0
#define MXT_CONFIG_T15_XSIZE              0
#define MXT_CONFIG_T15_YSIZE              0
#define MXT_CONFIG_T15_AKSCFG             0
#define MXT_CONFIG_T15_BLEN               0
#define MXT_CONFIG_T15_TCHTHR             0
#define MXT_CONFIG_T15_TCHDI              0
#define MXT_CONFIG_T15_RESERVED_0         0
#define MXT_CONFIG_T15_RESERVED_1         0

/* SPT_COMMSCONFIG_T18 */
#define MXT_CONFIG_T18_CTRL               1
#define MXT_CONFIG_T18_COMMAND            0

/* SPT_GPIOPWM_T19 */
#define MXT_CONFIG_T19_CTRL               0
#define MXT_CONFIG_T19_REPORTMASK         0
#define MXT_CONFIG_T19_DIR                0
#define MXT_CONFIG_T19_INTPULLUP          0
#define MXT_CONFIG_T19_OUT                0
#define MXT_CONFIG_T19_WAKE               0
#define MXT_CONFIG_T19_PWM                0
#define MXT_CONFIG_T19_PERIOD             0
#define MXT_CONFIG_T19_DUTY_0             0
#define MXT_CONFIG_T19_DUTY_1             0
#define MXT_CONFIG_T19_DUTY_2             0
#define MXT_CONFIG_T19_DUTY_3             0
#define MXT_CONFIG_T19_TRIGGER_0          0
#define MXT_CONFIG_T19_TRIGGER_1          0
#define MXT_CONFIG_T19_TRIGGER_2          0
#define MXT_CONFIG_T19_TRIGGER_3          0

/* TOUCH_PROXIMITY_T23 */
#define MXT_CONFIG_T23_CTRL               0
#define MXT_CONFIG_T23_XORIGIN            0
#define MXT_CONFIG_T23_YORIGIN            0
#define MXT_CONFIG_T23_XSIZE              0
#define MXT_CONFIG_T23_YSIZE              0
#define MXT_CONFIG_T23_RESERVED_0         0
#define MXT_CONFIG_T23_BLEN               0
#define MXT_CONFIG_T23_FXDDTHR_LS         0
#define MXT_CONFIG_T23_FXDDTHR_MS         0
#define MXT_CONFIG_T23_FXDDI              0
#define MXT_CONFIG_T23_AVERAGE            0
#define MXT_CONFIG_T23_MVNULLRATE_LS      0
#define MXT_CONFIG_T23_MVNULLRATE_MS      0
#define MXT_CONFIG_T23_MVDTHR_LS          0
#define MXT_CONFIG_T23_MVDTHR_MS          0

/* SPT_SELFTEST_T25 */
#define MXT_CONFIG_T25_CTRL               0
#define MXT_CONFIG_T25_CMD                0
#define MXT_CONFIG_T25_HISIGLIM_0_LS      0
#define MXT_CONFIG_T25_HISIGLIM_0_MS      0
#define MXT_CONFIG_T25_LOSIGLIM_0_LS      0
#define MXT_CONFIG_T25_LOSIGLIM_0_MS      0
#define MXT_CONFIG_T25_HISIGLIM_1_LS      0
#define MXT_CONFIG_T25_HISIGLIM_1_MS      0
#define MXT_CONFIG_T25_LOSIGLIM_1_LS      0
#define MXT_CONFIG_T25_LOSIGLIM_1_MS      0
#define MXT_CONFIG_T25_HISIGLIM_2_LS      0
#define MXT_CONFIG_T25_HISIGLIM_2_MS      0
#define MXT_CONFIG_T25_LOSIGLIM_2_LS      0
#define MXT_CONFIG_T25_LOSIGLIM_2_MS      0

/* PROCI_GRIPSUPPRESSION_T40 */
#define MXT_CONFIG_T40_CTRL               0
#define MXT_CONFIG_T40_XLOGRIP            0
#define MXT_CONFIG_T40_XHIGRIP            0
#define MXT_CONFIG_T40_YLOGRIP            0
#define MXT_CONFIG_T40_YHIGRIP            0

/* PROCI_TOUCHSUPPRESSION_T42 */
#define MXT_CONFIG_T42_CTRL               3
#define MXT_CONFIG_T42_APPRTHR            26
#define MXT_CONFIG_T42_MAXAPPRAREA        58
#define MXT_CONFIG_T42_MAXTCHAREA         96
#define MXT_CONFIG_T42_SUPSTRENGTH        208
#define MXT_CONFIG_T42_SUPEXTTO           0
#define MXT_CONFIG_T42_MAXNUMTCHS         0
#define MXT_CONFIG_T42_SHAPESTRENGTH      0

/* SPT_CTECONFIG_T46 */
#define MXT_CONFIG_T46_CTRL               0
#define MXT_CONFIG_T46_MODE               3
#define MXT_CONFIG_T46_IDLESYNCSPERX      35
#define MXT_CONFIG_T46_ACTVSYNCSPERX      35
#define MXT_CONFIG_T46_ADCSPERSYNC        0
#define MXT_CONFIG_T46_PULSESPERADC       0
#define MXT_CONFIG_T46_XSLEW              1
#define MXT_CONFIG_T46_SYNCDELAY_LS       0
#define MXT_CONFIG_T46_SYNCDELAY_MS       0

/* PROCI_STYLUS_T47 */
#define MXT_CONFIG_T47_CTRL               0
#define MXT_CONFIG_T47_CONTMIN            0
#define MXT_CONFIG_T47_CONTMAX            0
#define MXT_CONFIG_T47_STABILITY          0
#define MXT_CONFIG_T47_MAXTCHAREA         0
#define MXT_CONFIG_T47_AMPLTHR            0
#define MXT_CONFIG_T47_STYSHAPE           0
#define MXT_CONFIG_T47_HOVERSUP           0
#define MXT_CONFIG_T47_CONFTHR            0
#define MXT_CONFIG_T47_SYNCSPERX          0

/* PROCG_NOISESUPPRESSION_T48 */
#define MXT_CONFIG_T48_CTRL               3
#define MXT_CONFIG_T48_CFG                4
#define MXT_CONFIG_T48_CALCFG             64
#define MXT_CONFIG_T48_BASEFREQ           8
#define MXT_CONFIG_T48_RESERVED_0         0
#define MXT_CONFIG_T48_RESERVED_1         0
#define MXT_CONFIG_T48_RESERVED_2         0
#define MXT_CONFIG_T48_RESERVED_3         0
#define MXT_CONFIG_T48_MFFREQ_0           10
#define MXT_CONFIG_T48_MFFREQ_1           15
#define MXT_CONFIG_T48_RESERVED_4         0
#define MXT_CONFIG_T48_RESERVED_5         0
#define MXT_CONFIG_T48_RESERVED_6         0
#define MXT_CONFIG_T48_GCACTVINVLDADCS    6
#define MXT_CONFIG_T48_GCIDLEINVLDADCS    6
#define MXT_CONFIG_T48_RESERVED_6         0
#define MXT_CONFIG_T48_RESERVED_7         0
#define MXT_CONFIG_T48_GCMAXADCSPERX      100
#define MXT_CONFIG_T48_GCLIMITMIN         4
#define MXT_CONFIG_T48_GCLIMITMAX         64
#define MXT_CONFIG_T48_GCCOUNTMINTGT_MINI 10
#define MXT_CONFIG_T48_GCCOUNTMINTGT_MAX  0
#define MXT_CONFIG_T48_MFINVLDDIFFTHR     20
#define MXT_CONFIG_T48_MFINCADCSPXTHR_LS  5
#define MXT_CONFIG_T48_MFINCADCSPXTHR_MS  0
#define MXT_CONFIG_T48_MFERRORTHR_LS      25
#define MXT_CONFIG_T48_MFERRORTHR_MS      0
#define MXT_CONFIG_T48_SELFREQMAX         5
#define MXT_CONFIG_T48_RESERVED_8         0
#define MXT_CONFIG_T48_RESERVED_9         0
#define MXT_CONFIG_T48_RESERVED_10        0
#define MXT_CONFIG_T48_RESERVED_11        0
#define MXT_CONFIG_T48_RESERVED_12        0
#define MXT_CONFIG_T48_RESERVED_13        0
#define MXT_CONFIG_T48_BLEN               32
#define MXT_CONFIG_T48_TCHTHR             55
#define MXT_CONFIG_T48_TCHDI              2
#define MXT_CONFIG_T48_MOVHYSTI           5
#define MXT_CONFIG_T48_MOVHYSTN           2
#define MXT_CONFIG_T48_MOVFILTER          1
#define MXT_CONFIG_T48_NUMTOUCH           5
#define MXT_CONFIG_T48_MRGHYST            20
#define MXT_CONFIG_T48_MRGTHR             50
#define MXT_CONFIG_T48_XLOCLIP            0
#define MXT_CONFIG_T48_XHICLIP            0
#define MXT_CONFIG_T48_YLOCLIP            10
#define MXT_CONFIG_T48_YHICLIP            10
#define MXT_CONFIG_T48_XEDGECTRL          136
#define MXT_CONFIG_T48_XEDGEDIST          0
#define MXT_CONFIG_T48_YEDGECTRL          136
#define MXT_CONFIG_T48_YEDGEDIST          0
#define MXT_CONFIG_T48_JUMPLIMIT          25
#define MXT_CONFIG_T48_TCHHYST            15
#define MXT_CONFIG_T48_NEXTTCHDI          3


static const u8 mxt_config_t6_data[5]  = {
MXT_CONFIG_T06_RESET,
MXT_CONFIG_T06_BACKUPNV,
MXT_CONFIG_T06_CALIBRAT,
MXT_CONFIG_T06_REPORTALL,
MXT_CONFIG_T06_DIAGNOSTIC
};
static const u8 mxt_config_t38_data[8] = {
MXT_CONFIG_T38_DATA_0,
MXT_CONFIG_T38_DATA_1,
MXT_CONFIG_T38_DATA_2,
MXT_CONFIG_T38_DATA_3,
MXT_CONFIG_T38_DATA_4,
MXT_CONFIG_T38_DATA_5,
MXT_CONFIG_T38_DATA_6,
MXT_CONFIG_T38_DATA_7
};
static const u8 mxt_config_t7_data[3]  = {
MXT_CONFIG_T07_IDLEACQINT,
MXT_CONFIG_T07_ACTVACQINT,
MXT_CONFIG_T07_ACTV2IDLETO
};
static const u8 mxt_config_t8_data[10]  = {
MXT_CONFIG_T08_CHRGTIME,
MXT_CONFIG_T08_ATCHDRIFT,
MXT_CONFIG_T08_TCHDRIFT,
MXT_CONFIG_T08_DRIFTST,
MXT_CONFIG_T08_TCHAUTOCAL,
MXT_CONFIG_T08_SYNC,
MXT_CONFIG_T08_ATCHCALST,
MXT_CONFIG_T08_ATCHCALSTHR,
MXT_CONFIG_T08_ATCHFRCCALTHR,
MXT_CONFIG_T08_ATCHFRCCALRATIO
};
static const u8 mxt_config_t9_data[35]  = {
MXT_CONFIG_T09_CTRL,
MXT_CONFIG_T09_XORIGIN,
MXT_CONFIG_T09_YORIGIN,
MXT_CONFIG_T09_XSIZE,
MXT_CONFIG_T09_YSIZE,
MXT_CONFIG_T09_AKSCFG,
MXT_CONFIG_T09_BLEN,
MXT_CONFIG_T09_TCHTHR,
MXT_CONFIG_T09_TCHDI,
MXT_CONFIG_T09_ORIENT,
MXT_CONFIG_T09_MRGTIMEOUT,
MXT_CONFIG_T09_MOVHYSTI,
MXT_CONFIG_T09_MOVHYSTN,
MXT_CONFIG_T09_MOVFILTER,
MXT_CONFIG_T09_NUMTOUCH,
MXT_CONFIG_T09_MRGHYST,
MXT_CONFIG_T09_MRGTHR,
MXT_CONFIG_T09_AMPHYST,
MXT_CONFIG_T09_XRANGE_LO,
MXT_CONFIG_T09_XRANGE_HI,
MXT_CONFIG_T09_YRANGE_LO,
MXT_CONFIG_T09_YRANGE_HI,
MXT_CONFIG_T09_XLOCLIP,
MXT_CONFIG_T09_XHICLIP,
MXT_CONFIG_T09_YLOCLIP,
MXT_CONFIG_T09_YHICLIP,
MXT_CONFIG_T09_XEDGECTRL,
MXT_CONFIG_T09_XEDGEDIST,
MXT_CONFIG_T09_YEDGECTRL,
MXT_CONFIG_T09_YEDGEDIST,
MXT_CONFIG_T09_JUMPLIMIT,
MXT_CONFIG_T09_TCHHYST,
MXT_CONFIG_T09_XPITCH,
MXT_CONFIG_T09_YPITCH,
MXT_CONFIG_T09_NEXTTCHDI
};
static const u8 mxt_config_t15_data[11] = {
MXT_CONFIG_T15_CTRL,
MXT_CONFIG_T15_XORIGIN,
MXT_CONFIG_T15_YORIGIN,
MXT_CONFIG_T15_XSIZE,
MXT_CONFIG_T15_YSIZE,
MXT_CONFIG_T15_AKSCFG,
MXT_CONFIG_T15_BLEN,
MXT_CONFIG_T15_TCHTHR,
MXT_CONFIG_T15_TCHDI,
MXT_CONFIG_T15_RESERVED_0,
MXT_CONFIG_T15_RESERVED_1
};
static const u8 mxt_config_t18_data[2] = {
MXT_CONFIG_T18_CTRL,
MXT_CONFIG_T18_COMMAND
};
static const u8 mxt_config_t19_data[16] = {
MXT_CONFIG_T19_CTRL,
MXT_CONFIG_T19_REPORTMASK,
MXT_CONFIG_T19_DIR,
MXT_CONFIG_T19_INTPULLUP,
MXT_CONFIG_T19_OUT,
MXT_CONFIG_T19_WAKE,
MXT_CONFIG_T19_PWM,
MXT_CONFIG_T19_PERIOD,
MXT_CONFIG_T19_DUTY_0,
MXT_CONFIG_T19_DUTY_1,
MXT_CONFIG_T19_DUTY_2,
MXT_CONFIG_T19_DUTY_3,
MXT_CONFIG_T19_TRIGGER_0,
MXT_CONFIG_T19_TRIGGER_1,
MXT_CONFIG_T19_TRIGGER_2,
MXT_CONFIG_T19_TRIGGER_3
};
static const u8 mxt_config_t23_data[15] = {
MXT_CONFIG_T23_CTRL,
MXT_CONFIG_T23_XORIGIN,
MXT_CONFIG_T23_YORIGIN,
MXT_CONFIG_T23_XSIZE,
MXT_CONFIG_T23_YSIZE,
MXT_CONFIG_T23_RESERVED_0,
MXT_CONFIG_T23_BLEN,
MXT_CONFIG_T23_FXDDTHR_LS,
MXT_CONFIG_T23_FXDDTHR_MS,
MXT_CONFIG_T23_FXDDI,
MXT_CONFIG_T23_AVERAGE,
MXT_CONFIG_T23_MVNULLRATE_LS,
MXT_CONFIG_T23_MVNULLRATE_MS,
MXT_CONFIG_T23_MVDTHR_LS,
MXT_CONFIG_T23_MVDTHR_MS
};
static const u8 mxt_config_t25_data[14] = {
MXT_CONFIG_T25_CTRL,
MXT_CONFIG_T25_CMD,
MXT_CONFIG_T25_HISIGLIM_0_LS,
MXT_CONFIG_T25_HISIGLIM_0_MS,
MXT_CONFIG_T25_LOSIGLIM_0_LS,
MXT_CONFIG_T25_LOSIGLIM_0_MS,
MXT_CONFIG_T25_HISIGLIM_1_LS,
MXT_CONFIG_T25_HISIGLIM_1_MS,
MXT_CONFIG_T25_LOSIGLIM_1_LS,
MXT_CONFIG_T25_LOSIGLIM_1_MS,
MXT_CONFIG_T25_HISIGLIM_2_LS,
MXT_CONFIG_T25_HISIGLIM_2_MS,
MXT_CONFIG_T25_LOSIGLIM_2_LS,
MXT_CONFIG_T25_LOSIGLIM_2_MS
};
static const u8 mxt_config_t40_data[5] = {
MXT_CONFIG_T40_CTRL,
MXT_CONFIG_T40_XLOGRIP,
MXT_CONFIG_T40_XHIGRIP,
MXT_CONFIG_T40_YLOGRIP,
MXT_CONFIG_T40_YHIGRIP
};
static const u8 mxt_config_t42_data[8] = {
MXT_CONFIG_T42_CTRL,
MXT_CONFIG_T42_APPRTHR,
MXT_CONFIG_T42_MAXAPPRAREA,
MXT_CONFIG_T42_MAXTCHAREA,
MXT_CONFIG_T42_SUPSTRENGTH,
MXT_CONFIG_T42_SUPEXTTO,
MXT_CONFIG_T42_MAXNUMTCHS,
MXT_CONFIG_T42_SHAPESTRENGTH
};
static const u8 mxt_config_t46_data[9] = {
MXT_CONFIG_T46_CTRL,
MXT_CONFIG_T46_MODE,
MXT_CONFIG_T46_IDLESYNCSPERX,
MXT_CONFIG_T46_ACTVSYNCSPERX,
MXT_CONFIG_T46_ADCSPERSYNC,
MXT_CONFIG_T46_PULSESPERADC,
MXT_CONFIG_T46_XSLEW,
MXT_CONFIG_T46_SYNCDELAY_LS,
MXT_CONFIG_T46_SYNCDELAY_MS
};
static const u8 mxt_config_t47_data[10] = {
MXT_CONFIG_T47_CTRL,
MXT_CONFIG_T47_CONTMIN,
MXT_CONFIG_T47_CONTMAX,
MXT_CONFIG_T47_STABILITY,
MXT_CONFIG_T47_MAXTCHAREA,
MXT_CONFIG_T47_AMPLTHR,
MXT_CONFIG_T47_STYSHAPE,
MXT_CONFIG_T47_HOVERSUP,
MXT_CONFIG_T47_CONFTHR,
MXT_CONFIG_T47_SYNCSPERX
};
static const u8 mxt_config_t48_data[54] = {
MXT_CONFIG_T48_CTRL,
MXT_CONFIG_T48_CFG,
MXT_CONFIG_T48_CALCFG,
MXT_CONFIG_T48_BASEFREQ,
MXT_CONFIG_T48_RESERVED_0,
MXT_CONFIG_T48_RESERVED_1,
MXT_CONFIG_T48_RESERVED_2,
MXT_CONFIG_T48_RESERVED_3,
MXT_CONFIG_T48_MFFREQ_0,
MXT_CONFIG_T48_MFFREQ_1,
MXT_CONFIG_T48_RESERVED_4 ,
MXT_CONFIG_T48_RESERVED_5,
MXT_CONFIG_T48_RESERVED_6,
MXT_CONFIG_T48_GCACTVINVLDADCS,
MXT_CONFIG_T48_GCIDLEINVLDADCS,
MXT_CONFIG_T48_RESERVED_6,
MXT_CONFIG_T48_RESERVED_7,
MXT_CONFIG_T48_GCMAXADCSPERX,
MXT_CONFIG_T48_GCLIMITMIN,
MXT_CONFIG_T48_GCLIMITMAX,
MXT_CONFIG_T48_GCCOUNTMINTGT_MINI,
MXT_CONFIG_T48_GCCOUNTMINTGT_MAX,
MXT_CONFIG_T48_MFINVLDDIFFTHR,
MXT_CONFIG_T48_MFINCADCSPXTHR_LS,
MXT_CONFIG_T48_MFINCADCSPXTHR_MS,
MXT_CONFIG_T48_MFERRORTHR_LS,
MXT_CONFIG_T48_MFERRORTHR_MS,
MXT_CONFIG_T48_SELFREQMAX,
MXT_CONFIG_T48_RESERVED_8,
MXT_CONFIG_T48_RESERVED_9,
MXT_CONFIG_T48_RESERVED_10,
MXT_CONFIG_T48_RESERVED_11,
MXT_CONFIG_T48_RESERVED_12,
MXT_CONFIG_T48_RESERVED_13,
MXT_CONFIG_T48_BLEN,
MXT_CONFIG_T48_TCHTHR,
MXT_CONFIG_T48_TCHDI,
MXT_CONFIG_T48_MOVHYSTI,
MXT_CONFIG_T48_MOVHYSTN,
MXT_CONFIG_T48_MOVFILTER,
MXT_CONFIG_T48_NUMTOUCH,
MXT_CONFIG_T48_MRGHYST,
MXT_CONFIG_T48_MRGTHR,
MXT_CONFIG_T48_XLOCLIP,
MXT_CONFIG_T48_XHICLIP,
MXT_CONFIG_T48_YLOCLIP,
MXT_CONFIG_T48_YHICLIP,
MXT_CONFIG_T48_XEDGECTRL,
MXT_CONFIG_T48_XEDGEDIST,
MXT_CONFIG_T48_YEDGECTRL,
MXT_CONFIG_T48_YEDGEDIST,
MXT_CONFIG_T48_JUMPLIMIT,
MXT_CONFIG_T48_TCHHYST,
MXT_CONFIG_T48_NEXTTCHDI
};

#endif // _FJ_TOUCH_CONFIG_H_
