#
# Makefile for fujitsu proximity/illumi sensor devices that really don't fit anywhere else.
#
KBUILD_CFLAGS += -Iarch/arm/mach-msm

obj-$(CONFIG_FUJITSU_PROXIMITY_DRIVER) += proximity.o
obj-$(CONFIG_FUJITSU_ILLUMI_DRIVER) += light.o
